# SPDX-License-Identifier: Apache-2.0
"""
Relabel the per-episode language prompt of a LeRobot (GR00T) dataset so that the
prompt names which arm does the grasping.

Why
---
The block-stacking data was generated by a fixed policy that, per episode, picks
an *active* arm to grasp while the other arm only repositions its wrist camera.
Every episode currently shares one generic prompt, so the policy never learns the
left/right asymmetry. This script inspects the recorded gripper-close commands to
recover which arm grasped each cube and rewrites the prompt accordingly.

How the active arm is recovered
-------------------------------
The action vector is [left_arm(7), right_arm(7), left_gripper, right_gripper]
(see meta/modality.json). Only a grasping arm's gripper is commanded closed
(value -> 1.0); the passive arm's gripper stays at 0. The state machine always
grasps the BLUE cube first, then the ORANGE cube, so the earliest gripper-close
run identifies the blue-cube arm and the latest run the orange-cube arm. This
yields four classes:

    left          left arm grasps both cubes
    right         right arm grasps both cubes
    left_right    left grasps blue, right grasps orange   (bimanual)
    right_left    right grasps blue, left grasps orange    (bimanual)

GR00T resolves language per frame by reading the int column
`annotation.human.task_description` and looking it up in meta/tasks.jsonl
(see gr00t/data/dataset.py:get_language). We therefore append the new prompts to
tasks.jsonl and set every frame's annotation index (and task_index) to the class.

Output
------
A new dataset is written to --dst (the source is left untouched). Parquet files
are copied with only the two index columns changed; videos are symlinked by
default (use --copy-videos to duplicate them); all other meta files are copied.

Usage
-----
    python scripts/relabel_arm_prompts.py --src data --dst data_relabeled
    python scripts/relabel_arm_prompts.py --src data --dst data_relabeled --dry-run
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
from collections import Counter
from pathlib import Path

import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq

ANNOTATION_COL = "annotation.human.task_description"
TASK_INDEX_COL = "task_index"

# task_index -> prompt string. Index 0 keeps the original generic prompt (unused
# after relabeling but harmless); 1-4 are the arm-specific prompts.
PROMPTS = {
    1: "Using the left arm to stack the blue block onto the black block, then stack the orange block on top of the blue block.",
    2: "Using the right arm to stack the blue block onto the black block, then stack the orange block on top of the blue block.",
    3: "Using the left arm to stack the blue block onto the black block, then using the right arm to stack the orange block on top of the blue block.",
    4: "Using the right arm to stack the blue block onto the black block, then using the left arm to stack the orange block on top of the blue block.",
}
CLASS_TO_INDEX = {"left": 1, "right": 2, "left_right": 3, "right_left": 4}


def load_gripper_slices(src: Path) -> tuple[int, int]:
    """Return (left_gripper_idx, right_gripper_idx) into the action vector."""
    with open(src / "meta" / "modality.json") as f:
        action = json.load(f)["action"]
    lg = action["left_gripper"]
    rg = action["right_gripper"]
    # gripper modalities are width-1 here; take the start index.
    return lg["start"], rg["start"]


def gripper_runs(x: np.ndarray, thresh: float, min_len: int) -> list[tuple[int, int]]:
    """Contiguous runs where x > thresh, keeping only runs of length >= min_len."""
    on = x > thresh
    runs: list[tuple[int, int]] = []
    start: int | None = None
    for i, v in enumerate(on):
        if v and start is None:
            start = i
        elif not v and start is not None:
            if i - start >= min_len:
                runs.append((start, i - 1))
            start = None
    if start is not None and len(on) - start >= min_len:
        runs.append((start, len(on) - 1))
    return runs


def classify_episode(
    action: np.ndarray, lg_idx: int, rg_idx: int, min_len: int
) -> str | None:
    """Return one of left/right/left_right/right_left, or None if no grasp found."""
    events: list[tuple[int, str]] = []
    for arm, idx in (("left", lg_idx), ("right", rg_idx)):
        for s, _ in gripper_runs(action[:, idx], 0.5, min_len):
            events.append((s, arm))
    if not events:
        return None
    events.sort()
    blue_arm = events[0][1]   # earliest grasp == blue cube
    orange_arm = events[-1][1]  # latest grasp == orange cube
    if blue_arm == orange_arm:
        return blue_arm
    return f"{blue_arm}_{orange_arm}"


def action_matrix(table: pa.Table) -> np.ndarray:
    """Stack the list<double> 'action' column into a (T, D) array."""
    return np.array(table.column("action").to_pylist(), dtype=np.float64)


def write_meta(src: Path, dst: Path, label_counts: Counter) -> None:
    (dst / "meta").mkdir(parents=True, exist_ok=True)
    for name in os.listdir(src / "meta"):
        if name == "tasks.jsonl":
            continue
        s = src / "meta" / name
        if s.is_file():
            shutil.copy2(s, dst / "meta" / name)

    # tasks.jsonl: keep index 0 (original generic) + append the arm prompts.
    with open(src / "meta" / "tasks.jsonl") as f:
        original = [json.loads(line) for line in f if line.strip()]
    by_index = {row["task_index"]: row["task"] for row in original}
    for idx, prompt in PROMPTS.items():
        by_index[idx] = prompt
    with open(dst / "meta" / "tasks.jsonl", "w") as f:
        for idx in sorted(by_index):
            f.write(json.dumps({"task_index": idx, "task": by_index[idx]}) + "\n")

    # keep info.json's total_tasks consistent with tasks.jsonl
    info_path = dst / "meta" / "info.json"
    if info_path.exists():
        with open(info_path) as f:
            info = json.load(f)
        info["total_tasks"] = len(by_index)
        with open(info_path, "w") as f:
            json.dump(info, f, indent=4)


def link_or_copy_videos(src: Path, dst: Path, copy: bool) -> None:
    src_videos = src / "videos"
    if not src_videos.exists():
        return
    dst_videos = dst / "videos"
    if dst_videos.exists() or dst_videos.is_symlink():
        return
    if copy:
        shutil.copytree(src_videos, dst_videos)
    else:
        # Use a RELATIVE symlink so it resolves regardless of where the repo is
        # mounted (e.g. training runs in a container with the repo at a different
        # absolute path than this host). An absolute target would dangle there.
        rel_target = os.path.relpath(src_videos.resolve(), dst.resolve())
        os.symlink(rel_target, dst_videos)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--src", type=Path, default=Path("data"), help="Source dataset dir")
    p.add_argument("--dst", type=Path, default=Path("data_relabeled"), help="Output dataset dir")
    p.add_argument("--min-run-len", type=int, default=3, help="Min frames a gripper must stay closed to count as a grasp")
    p.add_argument("--copy-videos", action="store_true", help="Copy videos instead of symlinking")
    p.add_argument("--dry-run", action="store_true", help="Only analyze and report; write nothing")
    args = p.parse_args()

    src: Path = args.src
    dst: Path = args.dst
    lg_idx, rg_idx = load_gripper_slices(src)
    print(f"action gripper indices: left={lg_idx} right={rg_idx}")

    parquets = sorted((src / "data").rglob("episode_*.parquet"))
    print(f"found {len(parquets)} episode parquet files in {src/'data'}")

    label_counts: Counter = Counter()
    report: dict[str, dict] = {}

    if not args.dry_run:
        write_meta(src, dst, label_counts)
        link_or_copy_videos(src, dst, args.copy_videos)

    for i, f in enumerate(parquets):
        table = pq.read_table(f)
        action = action_matrix(table)
        cls = classify_episode(action, lg_idx, rg_idx, args.min_run_len)
        idx = CLASS_TO_INDEX.get(cls, 0)  # 0 == fallback generic (should not occur)
        label_counts[cls if cls else "none"] += 1
        rel = f.relative_to(src)
        report[str(rel)] = {"class": cls, "task_index": idx, "frames": table.num_rows}

        if args.dry_run:
            continue

        n = table.num_rows
        new_col = pa.array(np.full(n, idx, dtype=np.int64), type=pa.int64())
        for col in (ANNOTATION_COL, TASK_INDEX_COL):
            ci = table.schema.get_field_index(col)
            if ci >= 0:
                table = table.set_column(ci, col, new_col)
        out = dst / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        pq.write_table(table, out)

        if (i + 1) % 200 == 0:
            print(f"  processed {i + 1}/{len(parquets)}")

    print("\n=== label distribution ===")
    for k in ["left", "right", "left_right", "right_left", "none"]:
        if label_counts.get(k):
            print(f"  {k:12s} {label_counts[k]:5d}  -> task_index {CLASS_TO_INDEX.get(k, 0)}")
    print(f"  {'TOTAL':12s} {sum(label_counts.values()):5d}")

    if not args.dry_run:
        with open(dst / "meta" / "arm_labels.json", "w") as f:
            json.dump(report, f, indent=2)
        print(f"\nwrote relabeled dataset to {dst}")
        print(f"per-episode label map: {dst/'meta'/'arm_labels.json'}")
        print("tasks.jsonl prompts:")
        for idx, prompt in PROMPTS.items():
            print(f"  [{idx}] {prompt}")
    else:
        print("\n(dry run — nothing written)")


if __name__ == "__main__":
    main()
